= To Do Overview

- [ ] Iets van lettertype Arial vinden, voor de headings
- [ ] Correcties van Carla 2024.11.15 verwerken
** Bookchapters zijn toch twee woorden:Google serch geeft meteen aan: Bedoel je _Book Chapters_ ?
** In Publications, ook de title _Scientific Publications_ weg halen?
** In CV NL onder _Verdere informatie_: __Leuven,(België)__, 
- [ ] Toevoegen bedrijfsnaam, over alle pagina's, inclusief in het klein eronder, inclusief switchen NL-EN
- [ ] Toevoegen navigatie tussen pagina's home/cv/publications
- [ ] Toevoegen KVK nummer
- [ ] Uitzoeken waar url voorkeur `sieburgh.eu` (ipv `sieburgh-abc.nl`)
- [ ] Account aanmaken voor mail / url hosting
+
--
[%header,cols="2,1,1,2,4"]
|===
| Product | Mail | URL | Plan | Price
| Google Workspace | ✅ | ✅ | Business Starter | $6 USD
per user/month, 1-year commitment
| | | | Business Standard | $12 USD
per user/month, 1-year commitment
| | | | Business Plus | $18 USD
per user/month, 1-year commitment
| MicroSoft 365 | ✅ | ✅ |  Business Basic | $12.50 per user per month with an annual commitment
| | | | Business Premium | $22.00 per user per month with an annual commitment
|===

.MicroSoft
[sidebar]
====
To configure DNS settings for your domain, including email and web hosting, you need a Microsoft 365 Business subscription. The minimal plan that includes domain management and DNS configuration is Microsoft 365 Business Basic. This plan offers essential services such as:

- *Email Hosting*: Professional email through Exchange Online.
- *Web Hosting*: Integration with SharePoint for internal websites.
- *DNS Management*: Ability to add and manage custom domains.
With Microsoft 365 Business Basic, you can add your own domain, configure DNS records, and utilize services like Outlook for email and Teams for collaboration. 
MICROSOFT LEARN

For more advanced features, such as desktop versions of Office apps and additional security measures, consider higher-tier plans like Microsoft 365 Business Standard or Microsoft 365 Business Premium.
====

** [ ] One account / two accounts
** [ ] Wil je zelf admin zijn over je account?
** [ ] Credit Card Details nodig bij aanmaken / inrichten van Google / Microsoft omgeving
--

- [x] Links toegevoegd in `publications.adoc` onder _Public Debate_

- [x] Aanvullingen in de hoofdtekst voor de website.
+
--
__Wed, Nov 6, 1:03 PM__

Home page (hoofd /openings pagina) aanpassingen gedaan.
--

- [x] CV in NL toegevoegd aan web site.
__Wed, Nov 6, 1:03 PM__
+
--
__Wed, Nov 6, 1:03 PM__

En verder het nederlandstalige cv. Al met al wil ik, als we bij het cv de expertise handhaven – dat toch liever als een opsomming met komma’s houden (ook omdat daarin net wat andere info staat dan bij de expertise van de hoofdpagina).

Het zou ook kunnen om die info uiteindelijk niet in het cv te zetten. Maar het uitgangspunt van het cv is dat het een zelfstandig leesbaar document is, en tegen die achtergrond is het wellicht juist goed om het te behouden
--
+
[sidebar]
--
Mijn gedachte was dat het cv als pdf als bijlage op de website zou komen, evenals de lijst van publicaties. Ik weet niet wat de reden ervoor is om dat anders te doen (ik heb er geen bezwaar tegen maar ben wel benieuwd). Ook als het cv en de publicatielijst niet als pdf-bijlage worden meegeleverd, heeft de gedachte “het is een eigenstandig stuk info” voor mij wel meerwaarde.
--


- [x] CV in UK opsomming met comma's aanpassen.
